# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#theme: minimal-mistakes-jekyll

#minimal-mistakes_skin: neon
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emmanuel Lugadilu
email: emmanuellugadilu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Cyber security enthusiast | software developer
twitter_username: ELugadilu
github_username: Lugadilu
minimal_mistakes_skin: neon
#skin: dark
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _projects
  -_lab-challenges

 

# Exclude from processing.

 collections:
  projects:
    output: true
    permalink: /projects/:title/

collections:
  lab-challenges:
    output: true
    permalink: /lab-challenges/:title/
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Emmanuel Lugadilu"
  avatar : "/assets/images/passport.jpg"
  bio    : "Cyber security enthusiast, web developer."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/ELugadilu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Lugadilu"
    - label: "linkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "www.linkedin.com/in/elugadilu"

footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/ELugadilu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Lugadilu"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
